name: CI

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: [ main ]

env:
  prerelease: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      id: semver
      with:
        tag_prefix: ""
    - name: Branch Name
      run: |
        if [ "$prerelease" = true ]
        then
          echo "##[set-output name=branch;]-${GITHUB_REF#refs/heads/}"
        fi
      id: branchname
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: octopusdeploytest
        IMAGE_TAG: octotest:${{steps.semver.outputs.version}}${{steps.branchname.outputs.branch}}
      run: |
        docker build --file src/Dockerfile --tag "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" ./src
