name: CI

on:
  
  workflow_dispatch:
    
  #push:
  #  branches: 
  #    - "**"

env:
  prerelease: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      # You may pin to the exact commit or the version.
      # uses: PaulHatch/semantic-version@0c47e4e1069ada118d9a5d5a163d72735a251d0c
      uses: PaulHatch/semantic-version@v5.0.0-alpha
      id: semver
      with:
        tag_prefix: ""
        
    - name: Branch Name
      run: |
        if [ "$prerelease" = true ]
        then
          echo "##[set-output name=branch;]-${GITHUB_REF#refs/heads/}"
        fi
      id: branchname
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: octotest
        IMAGE_TAG: ${{steps.semver.outputs.version}}${{steps.branchname.outputs.branch}}
      run: |
        docker build --file src/Dockerfile --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./src
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    - name: Tag version
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{steps.semver.outputs.version}}
        tag_prefix: "v"
