name: CI

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: [ main ]

env:
  prerelease: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      id: semver
      with:
        tag_prefix: ""
    - name: Branch Name
      run: |
        if [ "$prerelease" = false ]
        then
          echo "##[set-output name=branch;]-${GITHUB_REF#refs/heads/}"
        fi
      id: branchname
    - name: Build the Docker image
      run: docker build ./src --file src/Dockerfile --tag octotest:${{steps.semver.outputs.version}}${{steps.branchname.outputs.branch}}
