# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  DOTNET_ROLL_FORWARD: Major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
          versionSpec: '5.1.x'    
      
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13

    - name: Display version
      run: |
        echo SemVer: ${{ needs.calculate-version.outputs.semVer }}
